# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-30 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_auto_20181029_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
