# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_auto_20181030_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.Categoria', verbose_name='Categoria'),
        ),
    ]
