# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-09 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_auto_20181101_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
