# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_auto_20181109_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
