# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_auto_20181123_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kilogramos'), (2, 'Metros'), (3, 'Unidad'), (4, 'Litros')], null=True),
        ),
    ]
