# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_auto_20181123_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenes',
            field=models.ImageField(default='images/producto-sin-imagen.jpg', null=True, upload_to='images/'),
        ),
    ]
